import type { DocBlock } from '@tesyl/content/docs-types';
import { headingId } from '@tesyl/content/screean-docs';
import { CodeBlock } from './code-block';
import { highlight } from './highlight';

// Renders the DocBlock union. Content lives in packages/content; this file
// is the only place that decides what a block looks like.
//
// Server-rendered except for `code`, which delegates to the client
// CodeBlock for its copy button — so the samples are in the initial HTML
// and readable (and indexable) before any JavaScript runs.

// Inline markup in content strings: `code` spans and **bold**.
//
// Content files stay readable as prose — no JSX, no HTML — so the two
// delimiters are resolved here. Code is applied first and its contents are
// left alone, so a `**` inside a code span stays literal rather than
// turning into emphasis.
const withBold = (text: string, keyPrefix: string): React.ReactNode[] =>
  text.split('**').map((part, i) =>
    i % 2 === 1 ? <strong key={`${keyPrefix}b${i}`}>{part}</strong> : part,
  );

const withInlineMarkup = (text: string): React.ReactNode =>
  text.split('`').map((part, i) =>
    i % 2 === 1 ? (
      <code key={i} className="doc-inline-code">
        {part}
      </code>
    ) : (
      withBold(part, String(i))
    ),
  );

const Block = ({ block }: { block: DocBlock }): React.JSX.Element | null => {
  switch (block.kind) {
    case 'p':
      return <p className="doc-p">{withInlineMarkup(block.text)}</p>;

    case 'h3':
      // The id is generated by the same helper the "on this page" rail
      // uses, so the two can never drift apart.
      return (
        <h3 className="doc-h3" id={headingId(block.text)}>
          {block.text}
        </h3>
      );

    case 'code':
      // Highlighted here (server) so no highlighter ships to the browser.
      return (
        <CodeBlock
          code={block.code}
          label={block.label}
          html={highlight(block.code, block.label).html}
        />
      );

    case 'list':
      return (
        <ul className="doc-list">
          {block.items.map((item, i) => (
            <li key={i}>{withInlineMarkup(item)}</li>
          ))}
        </ul>
      );

    case 'note':
      return (
        <aside className={`doc-note doc-note--${block.tone}`}>
          <strong className="doc-note-title">{block.title}</strong>
          <span className="doc-note-text">{withInlineMarkup(block.text)}</span>
        </aside>
      );

    case 'table':
      return (
        // Wide tables scroll inside their own container rather than
        // pushing the page into a horizontal scroll.
        <div className="doc-table-wrap">
          <table className="doc-table">
            <thead>
              <tr>
                {block.head.map((h) => (
                  <th key={h}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {block.rows.map((row, i) => (
                <tr key={i}>
                  {row.map((cell, j) => (
                    <td key={j}>{withInlineMarkup(cell)}</td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      );

    case 'api':
      return (
        <div className="doc-api">
          <div className="doc-api-head">
            <code className="doc-api-name">{block.name}</code>
            <code className="doc-api-type">{block.type}</code>
            {block.required ? <span className="doc-api-tag">required</span> : null}
            {block.defaultsTo ? (
              <span className="doc-api-default">default {block.defaultsTo}</span>
            ) : null}
          </div>
          {block.body.map((line, i) => (
            <p key={i} className="doc-api-body">
              {withInlineMarkup(line)}
            </p>
          ))}
        </div>
      );

    default:
      return null;
  }
};

export const DocBlocks = ({
  blocks,
}: {
  blocks: ReadonlyArray<DocBlock>;
}): React.JSX.Element => (
  <>
    {blocks.map((block, i) => (
      <Block key={i} block={block} />
    ))}
  </>
);
