import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  // The content package ships raw TypeScript, so Next compiles it in place.
  transpilePackages: ['@tesyl/content'],

  // typedRoutes is off on purpose. Every route here is generated by mapping
  // over DESIGN_ROUTES, so the hrefs are template literals that typed routes
  // cannot narrow. Casting at each call site would add noise and prove
  // nothing. Turn it back on if this app ever gets hand-written routes.
  typedRoutes: false,
};

export default nextConfig;
